### ISSUE TITLE
Track Table

### ISSUE THREAD

**Issue by seankwilliams** [codefordenver/Comrad#137] opened 2018-09-25 02:25 UTC
Build the React Component for the Track Table on the main page of the Music Library.

Wireframe: https://drive.google.com/file/d/1Kk1qHuS-fNra4_emvOoQcK_BRkqqtSrA/view

**Comment by dzimmerman902** [comment] 2018-10-12 19:14
Duplicate of #176, closing for now

**Closed by dzimmerman902** 2018-10-12 19:14 UTC
Labels: Components, In Progress
